### ISSUE TITLE
XLL.REFTEXT default A1 parameter value

### ISSUE THREAD

**Issue by igitur** [xlladdins/xll#11]
Hi Keith,

Digging into your projects now.

I found `XLL.REFTEXT`, which could be useful for me for various cases. Just wondering whether the default value of the second parameter (`A1`) shouldn't rather be `TRUE` instead of `FALSE`. I would think that `A1` style references are much more common than `R1C1` style references.

Ref: https://github.com/xlladdins/xll/blob/c77ac69b65fc978f1ed8dc2eb7428bcc2c9021a0/xll/macrofun/xll_function.cpp#L179

**Comment by keithalewis** [comment]
Hi Beige Buffalo,
I agree with you but I’m just following the documentation https://xlladdins.github.io/Excel4Macros/reftext.html. 
Unlike humans, the Excel 4 macro languages prefers R1C1 style references.
-Keith

From: Francois Botha
Sent: Wednesday, August 11, 2021 2:37 AM
To: xlladdins/xll
Cc: Subscribed
Subject: [xlladdins/xll] XLL.REFTEXT default A1 parameter value (#11)

Hi Keith,
Digging into your projects now.
I found XLL.REFTEXT, which could be useful for me for various cases. Just wondering whether the default value of the second parameter (A1) shouldn't rather be TRUE instead of FALSE. I would think that A1 style references are much more common than R1C1 style references.
Ref: https://github.com/xlladdins/xll/blob/c77ac69b65fc978f1ed8dc2eb7428bcc2c9021a0/xll/macrofun/xll_function.cpp#L179
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by igitur** [comment]
Oooh OK. Didn't know you were implementing existing macros. I'd never heard of these Excel 4 macros before.

Ok, all good, keep as is. Thanks

**Comment by igitur** [comment]
And we'll have to get you a fight name too ;-)
