### ISSUE TITLE
Excel exceptions with xll_template

### ISSUE THREAD

**Issue by ripittard** [xlladdins/xll#14]
I am new to using github, VS Studio and have not used c/c++ for 20 years so I am a bit rusty.

I downloaded thezip file and ran the xll_template.sln using VS 2022.  Everthing seems to compile fine - no errors, however when I run in debug  it is a mess with lots of errors messages in the immediate window.  Many exceptions are thrown.  I amd running Excel 2010 on Windows 10 (64-bit).

The comile debug outputs are attached.
[output from debug immediate window.txt](https://github.com/xlladdins/xll/files/7720656/output.from.debug.immediate.window.txt)
[output from build.txt](https://github.com/xlladdins/xll/files/7720654/output.from.build.txt)

Any help would be appreciated.

Thanks

**Comment by keithalewis** [comment]
The build looks fine. The debug output is typical. The default whine level reports exceptions thrown by Excel.exe. As long as you don't see your code throwing unhandled exceptions you are good.
Debug builds also check for memory leaks. Use Ctrl-F to search for 'leak' in the output window to find those. See https://github.com/xlladdins/xll#memory-leaks.
Welcome back to the C++ world. A lot has happened since C++11. It is astounding to me how many brilliant people devote their unpaid time to keep improving the language. It is the 8-th Wonder of the World IMHO.
Here is a reference to help get you back up to speed: https://docs.microsoft.com/en-us/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=msvc-170
