### ISSUE TITLE
E0020: identifiers "Move" and "ApplyStyle" is undefined in paste.cpp

### ISSUE THREAD

**Issue by rentocika** [xlladdins/xll#4]
Hello!
I try to compile my project with last commits in xll and I've errors in paste.cpp:
E0020: identifier "Move" is undefined in paste.cpp on lines from 35 to 358. #include "spreadsheet.h" is present. How to fix this? Thank you!

**Comment by keithalewis** [comment]
Who needs CI when I've got you? :-). The immediate solution is to roll back to the last release that worked for you.  I've been doing some major restructuring to unify the spreadsheet, documentation, and paste function generation. My bad for doing that in master and checking in half-baked code.
In the future I will make a branch and keep master in good working order. Sorry about that!

**Comment by keithalewis** [comment]
You should be good now. I checked in a working version to master and will work on a different branch until the refactoring is done.

**Comment by rentocika** [comment]
There is still 2 errors in paste.cpp in lines 14 and 62:
C2760 syntax error: unexpected token '<', need 'declaration'.

**Comment by keithalewis** [comment]
You need 64-bit Excel. I may support 32-bit in the future, but not many people still use that.

**Comment by rentocika** [comment]
Yes, in 64-bit configuration xll compile with no erros. And how to hard fix xll for 32-bit version? Thank you!

**Comment by keithalewis** [comment]
About $200 hard, but you can always roll back to an earlier version

**Comment by rentocika** [comment]
Ok, understand. Which commits is latest for normal 32-bit compilation? Thanks

**Comment by keithalewis** [comment]
The master branch should work with 32-bit Excel now. I moved all the new goodies I've been working to [xll_macrofun](https://github.com/xlladdins/xll_macrofun). 
A breaking change is that specifying arguments to add-ins now uses `Arguments` instead of `Args`. That was the odd-man-out with naming conventions for preparing arguments for `xlfRegister`. Use Ctrl-H to replace `.Args(` with `.Arguments(` and you should be good to go.
You now owe me a drink the next time you are in New York. Столичная martini, with a twist and the shadow of a vermouth bottle passed over it.

**Comment by keithalewis** [comment]
I've updated the code for 32-bit builds. `git submodule update --recursive` should get you the latest.
Let me know if that does not resolve your problems.
